In [26]:
import cv2,os


data_path=r'C:\Users\warunajith\Documents\CNN Models\data\test'
categories=os.listdir(data_path)
labels=[i for i in range(len(categories))]

label_dict={} #empty dictionary

for i in range(len(categories)):
    label_dict[categories[i]]=labels[i]

print(label_dict)
print(categories)
print(labels)

{'angry': 0, 'disgust': 1, 'fear': 2, 'happy': 3, 'neutral': 4, 'sad': 5, 'surprise': 6}
['angry', 'disgust', 'fear', 'happy', 'neutral', 'sad', 'surprise']
[0, 1, 2, 3, 4, 5, 6]


In [27]:
img_size=48

test_data=[]
test_target=[]

for category in categories:
    folder_path=os.path.join(data_path,category)
    img_names=os.listdir(folder_path)
    
    for img_name in img_names:
        img_path=os.path.join(folder_path,img_name)
        img=cv2.imread(img_path)
        
        try:
            gray=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
            test_data.append(gray)
            test_target.append(label_dict[category])
            
        except Exception as e:
            print(e)

In [28]:
import numpy as np

test_data=np.array(test_data)
test_target=np.array(test_target)

In [29]:
print(test_data.shape,test_target.shape)

(7178, 48, 48) (7178,)


In [30]:
test_data_new=test_data/255.0
print(test_data_new.shape)
test_data_new=np.reshape(test_data_new,(test_data_new.shape[0],img_size,img_size,1))



(7178, 48, 48)


In [31]:
from keras.utils import np_utils

test_target_new=np_utils.to_categorical(test_target)
print(test_target_new.shape)

(7178, 7)


In [32]:
np.save('test_data',test_data_new)
np.save('test_target',test_target_new)

In [33]:
print(test_data_new.shape)


(7178, 48, 48, 1)


In [34]:
print(test_target_new[0:5,:])

[[1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]]


In [35]:
print(test_target_new.shape)

(7178, 7)
