In [3]:
import cv2,os


data_path=r'C:\Users\warunajith\Documents\CNN Models\data\train'
categories=os.listdir(data_path)
labels=[i for i in range(len(categories))]

label_dict={} #empty dictionary

for i in range(len(categories)):
    label_dict[categories[i]]=labels[i]

print(label_dict)
print(categories)
print(labels)

{'angry': 0, 'disgust': 1, 'fear': 2, 'happy': 3, 'neutral': 4, 'sad': 5, 'surprise': 6}
['angry', 'disgust', 'fear', 'happy', 'neutral', 'sad', 'surprise']
[0, 1, 2, 3, 4, 5, 6]


In [4]:
img_size=48

train_data=[]
train_target=[]

for category in categories:
    folder_path=os.path.join(data_path,category)
    img_names=os.listdir(folder_path)
    
    for img_name in img_names:
        img_path=os.path.join(folder_path,img_name)
        img=cv2.imread(img_path)
        
        try:
            gray=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
            train_data.append(gray)
            train_target.append(label_dict[category])
            
        except Exception as e:
            print(e)

In [5]:
import numpy as np

train_data=np.array(train_data)
train_target=np.array(train_target)

In [6]:
print(train_data.shape,train_target.shape)

(28709, 48, 48) (28709,)


In [11]:
train_data_new=train_data/255.0
print(train_data_new.shape)
train_data_new=np.reshape(train_data_new,(train_data_new.shape[0],img_size,img_size,1))

from keras.utils import np_utils

train_target_new=np_utils.to_categorical(train_target)
print(train_target_new.shape)

(28709, 48, 48)
(28709, 7)


In [8]:
np.save('train_data',train_data_new)
np.save('train_target',train_target_new)

In [9]:
print(train_target_new.shape)

(28709, 7)


In [10]:
print(train_data_new[0:5,:])

[[[[0.19607843]
   [0.1254902 ]
   [0.05882353]
   ...
   [0.52156863]
   [0.59215686]
   [0.3372549 ]]

  [[0.22352941]
   [0.13333333]
   [0.08627451]
   ...
   [0.54117647]
   [0.59215686]
   [0.34901961]]

  [[0.23921569]
   [0.11764706]
   [0.09411765]
   ...
   [0.55686275]
   [0.58431373]
   [0.34901961]]

  ...

  [[0.40392157]
   [0.39215686]
   [0.39215686]
   ...
   [0.58431373]
   [0.40784314]
   [0.33333333]]

  [[0.41960784]
   [0.43529412]
   [0.44313725]
   ...
   [0.59215686]
   [0.47058824]
   [0.3372549 ]]

  [[0.40784314]
   [0.40784314]
   [0.43921569]
   ...
   [0.56078431]
   [0.53333333]
   [0.3254902 ]]]


 [[[0.11372549]
   [0.09411765]
   [0.11372549]
   ...
   [0.04313725]
   [0.04705882]
   [0.06666667]]

  [[0.06666667]
   [0.05490196]
   [0.05490196]
   ...
   [0.05882353]
   [0.07843137]
   [0.09019608]]

  [[0.        ]
   [0.01568627]
   [0.01176471]
   ...
   [0.12941176]
   [0.1372549 ]
   [0.09019608]]

  ...

  [[0.98039216]
   [0.97254902]
   [0.9